apiVersion: apps/v1
kind: Deployment
metadata:
 name: gitlab-gke-cicd
 labels:
   app: python
spec:
 replicas: 1
 selector:
   matchLabels:
     app: python
 template:
   metadata:
     labels:
       app: python
   spec:
     containers:
       - name: python-hello-world
         image: gcr.io/apiVersion: apps/v1
kind: Deployment
metadata:
 name: gitlab-gke-cicd
 labels:
   app: python
spec:
 replicas: 1
 selector:
   matchLabels:
     app: python
 template:
   metadata:
     labels:
       app: python
   spec:
     containers:
       - name: python-hello-world
         image: gcr.io/apiVersion: apps/v1
kind: Deployment
metadata:
 name: gitlab-gke-cicd
 labels:
   app: python
spec:
 replicas: 1
 selector:
   matchLabels:
     app: python
 template:
   metadata:
     labels:
       app: python
   spec:
     containers:
       - name: python-hello-world
         image: gcr.io/My project 777/github-gke-cicd:<VERSION>
         imagePullPolicy: Always
         ports:
           - containerPort: 8080
         readinessProbe:
           httpGet:
             path: /
             port: 8080
           initialDelaySeconds: 5
           timeoutSeconds: 5
           periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: python
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: python/gitlab-gke-cicd:<VERSION>
         imagePullPolicy: Always
         ports:
           - containerPort: 8080
         readinessProbe:
           httpGet:
             path: /
             port: 8080
           initialDelaySeconds: 5
           timeoutSeconds: 5
           periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: python
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: python/github-gke-cicd:<VERSION>
         imagePullPolicy: Always
         ports:
           - containerPort: 8080
         readinessProbe:
           httpGet:
             path: /
             port: 8080
           initialDelaySeconds: 5
           timeoutSeconds: 5
           periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: python
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: python
